---
#
# This module logically implements RE-ENTRANT double for loops
#   with_items:
#     range (node_low_idx, node_hi_idx)
#     range (pod_low_idx, pod_hi_idx)
# Each iteration executes one item, and each re-entrance
# continues where it left off.
#
- block:
  - name:
    set_fact:
        all_run_done: False

  - name: Increment pod_idx
    set_fact:
        pod_idx: "{{resource_state.resources[0].status.pod_idx|int +1 }}"

  - name: Read previous node_idx
    set_fact:
       node_idx: "{{resource_state.resources[0].status.node_idx|int}}"

  - block: 
    #
    # This block starts a new node loop
    #
    - name: Increment node_idx
      set_fact:
        node_idx: "{{node_idx|int + 1}}"

    - name: Check node loop for ending condition
      set_fact:
        all_run_done: True
      when: "node_idx|int > resource_state.resources[0].status.node_hi_idx|int"

    #
    # Reset pod_idx AFTER node_idx tasks above, else cond change
    # causes it to skip node_idx tasks
    #
    - name: Reset pod_idx to pod_low_idx
      set_fact:
        pod_idx: "{{resource_state.resources[0].status.pod_low_idx}}"

    when: "pod_idx|int > resource_state.resources[0].status.pod_hi_idx|int"

  - block:
    # 
    # All done
    #
    - name: Unpause pods to complete
      command: "redis-cli set start done"

    - name: Change state to proceed to exit
      operator_sdk.util.k8s_status:
          api_version: ripsaw.cloudbulldozer.io/v1alpha1
          kind: Benchmark
          name: "{{ meta.name }}"
          namespace: "{{ operator_namespace }}"
          status:
            state: Set Running

    when: all_run_done == True

  - block:
    # 
    # More round(s) to run.
    #
    - name: Send redis restart signal
      command: "redis-cli set start restart"

    - name: Reset redis num_completion
      command: "redis-cli set num_completion 0"

    # New node_idx value on new node loop ONLY. But we simply write every time.
    - name: Set next run node_idx
      command: "redis-cli set node_idx {{node_idx}}"

    - name: Set next run pod_idx
      command: "redis-cli set pod_idx {{pod_idx}}"

    - name: Change state to run next round
      operator_sdk.util.k8s_status:
          api_version: ripsaw.cloudbulldozer.io/v1alpha1
          kind: Benchmark
          name: "{{ meta.name }}"
          namespace: "{{ operator_namespace }}"
          status:
            state: Clients Running
            pod_idx: "{{pod_idx}}"
            node_idx: "{{node_idx}}"

    when: all_run_done == False

  when: resource_state.resources[0].status.state == "Run Next Set"

