---

- block:
  #
  # Entry Condition: 
  #    1. A previous task has set 'node_idx' and 'pod_idx' in redis
  #    2. All cliest are polling for 'start' to run its workoad
  # Output: Clients with node_idx <= redis node_idx && pod_idx <= redis pod_ix
  #

  - name: Signal group to run
    command: "redis-cli set start true "

  - name: Update state to "Set Running"
    operator_sdk.util.k8s_status:
      api_version: ripsaw.cloudbulldozer.io/v1alpha1
      kind: Benchmark
      name: "{{ meta.name }}"
      namespace: "{{ operator_namespace }}"
      status:
        state: Set Running

  - name: debug 2
    command: "redis-cli set state Set_Running"

  when: resource_state.resources[0].status.state == "Clients Running"

