apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: uperf-benchmark
  namespace: my-ripsaw
spec:
  clustername: myk8scluster
  #elasticsearch:
  #   server: elk.server.com
  #   port: 9200
  #test_user: username_to_attach_to_metadata
  workload:
    # cleanup: true
    name: uperf
    args:
      serviceip: false
      hostnetwork: false
      networkpolicy: false
      pin: false
      multus:
        enabled: false
      pin_server: "node-0"
      pin_client: "node-1"
      samples: 1
      kind: pod
      pair: 1
      test_types:
        - stream
      protos:
        - tcp
      sizes:
        - 16384
      nthrs:
        - 1
      runtime: 30

      # The following variables are for scale uperf.
      # The scale mode will be activated with 'node_range' defined.
      
      # colocate: True 
      # density_range: [1, 32]
      # node_range: [1, 10]
      # step_size: log2
      #   Valid step_size values are: addN or log2
      #   N can be any decimal number
      #   Enumeration examples:
      #      add1:  1,2,3,4 ,,,
      #      add2:  1,3,5,7 ...
      #      add10: 1,11,21,31 ...
      #      log2:  1,2,4,8,16,32 ,,,
      # excluded_node: [ worker001 ]

